framework:

  csrf_protection: true
  translator:
    fallbacks: ~
  default_locale: "en_gb"

  secret: "THISISSECRET"

  router:
    resource: "routes/routing.yml"
    strict_requirements: ~

  session:
    storage_id: session.storage.php_bridge
    handler_id: ~

  ide: sublime

sensio_framework_extra:
  request: { converters: true }

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        url: '%env(DATABASE_URL)%'

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        auto_mapping: true
        mappings:
          WF:
            type: annotation
            dir: /app/Uniwise/Doctrine/Entity
            prefix: Uniwise\Doctrine\Entity
            is_bundle: false

fos_rest:
  serializer:
    serialize_null: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  body_listener:
    decoders:
      json: fos_rest.decoder.json
      xml: fos_rest.decoder.xml
  body_converter:
    enabled: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Service
  Uniwise\Symfony\Service\:
    resource: '/app/Uniwise/Symfony/Service/*'
    public: true

  #Controller
  Uniwise\Symfony\Bundle\ApiBundle\Controller\:
    resource: '/app/Uniwise/Symfony/Bundle/ApiBundle/Controller/*'
    tags: [ 'controller.service_arguments' ]
    calls:
      - [ setContainer, [ "@service_container" ] ]

  #Repository
  Uniwise\Doctrine\Entity\:
    resource: '/app/Uniwise/Doctrine/Entity/*'
    public: true
    exclude: [ '/app/Uniwise/Doctrine/Entity/Car.php' ]
